[[news]]
date = "2025-07"
content = "Our paper on Sufficiency-guided Continuous Adaptive Reasoning was submitted to ICML 2026"

[[news]]
date = "2025-07"
content = "Our paper on Code Translation was submitted to ICML 2026"

[[news]]
date = "2025-07"
content = "One paper accepted by CCL 2025 as Oral presentation"

[[news]]
date = "2025-05"
content = "One paper accepted by ICML 2025"

[[news]]
date = "2025-05"
content = "One paper accepted by ACL 2025"

[[news]]
date = "2025-04"
content = "Won Second Place in CCL25-Eval Task 10 (2/659)"

[[news]]
date = "2025-03"
content = "Won Sixth Place in Digital China Innovation Contest (National Level)"
