[[news]]
date = "2025-07"
content = "关于基于充分性的连续自适应推理的论文投稿至ICML 2026"

[[news]]
date = "2025-07"
content = "关于代码翻译的论文投稿至ICML 2026"

[[news]]
date = "2025-07"
content = "一篇论文被CCL 2025接收为Oral报告"

[[news]]
date = "2025-05"
content = "一篇论文被ICML 2025接收"

[[news]]
date = "2025-05"
content = "一篇论文被ACL 2025接收"

[[news]]
date = "2025-04"
content = "获得CCL25-Eval任务10第二名（2/659）"

[[news]]
date = "2025-03"
content = "获得数字中国创新大赛数字安全赛道第六名（国家级）"
